### PR TITLE
Make boringtun work with `wg syncconf`

### PR DESCRIPTION
**Pull request by jodevsa**
Hi,

Still **WIP**. It still doesn't compile. Before I fix the errors can I get some feedback if this is how this should be fixed?

### CODE REVIEW

**Comment by Noah-Kennedy** [comment]
@jodevsa it's mostly syntax/semantics errors. Are you experienced with using Rust?

**Comment by jodevsa** [comment]
@Noah-Kennedy  I'm aware of the syntax errors. I would like to get your feedback on my logic. After that I can figure out the syntax/semantics :)

**Comment by Noah-Kennedy** [comment]
Oh ok. We get a lot of PRs from people who don't know rust and just straight up copied some JS or Go code over, so I wasn't sure (the missing semicolon kinda threw me off lol).

**Comment by Noah-Kennedy** [comment]
What exactly regarding the logic do you want feedback on?

**Comment by jodevsa** [comment]
> Oh ok. We get a lot of PRs from people who don't know rust and just straight up copied some JS or Go code over, so I wasn't sure (the missing semicolon kinda threw me off lol).

Haha, don't worry I'll make sure that my code compiles but please check my logic first :) 


So I'm trying to make `wg syncconf` work:

In my changes I'm checking if any of the attributes `endpoint, allowed_ips, or keep_alive` have changed; if changed, I'm deleting the peer and then the code will continue with the flow of creating the peer from scratch. I'm not familiar with the code which is why I wanted to check if the logic is right :)

**Comment by Noah-Kennedy** [comment]
Hah, I'm actually a bit new to some of this code as well. What you are doing _looks_ correct, but you might go through a bit of trial and error here. I'd get this to compile first and then see if it works ;).

**Comment by jodevsa** [comment]
no time to work on this and no longer needed

**Pull request closed without merging**
