### PR TITLE
Fix build errors on iOS

### PR DESCRIPTION
**Pull request by protonjohn**
This addresses issue #254.

### CODE REVIEW

**Comment by Noah-Kennedy** [comment]
@protonjohn This branch has merge conflicts

**Comment by protonjohn** [comment]
Fixed, my apologies. I had based it off of the previous release version

**Comment by Noah-Kennedy** [comment]
@protonjohn CI is failing because you need to run `cargo fmt`.

**Comment by Noah-Kennedy** [comment]
@protonjohn could you please fix the fmt issue? This has been open for a while and I'd like to either get this in or close this.

**Comment by Noah-Kennedy** [comment]
Closed due to inactivity.

**Pull request closed without merging**
