### PR TITLE
.cargo/config.toml: Add llvm option slp back

### PR DESCRIPTION
**Pull request by bjzhjing**
Fixes: 3396860d5f51 ("emit=asm breaks clippy, and is unnecessary")

Commit 3396860d5f51 deletes
RUSTFLAG "llvm-args=-slp-recursion-max-depth" from config file by
mistake and causes the benchmark by running "cargo +nightly bench"
with performance down. Add this flag to get performance back.

Signed-off-by: Cathy Zhang <cathy.zhang@intel.com>

### CODE REVIEW

**Comment by Noah-Kennedy** [comment]
@bjzhjing how much does this improve performance? Breaking clippy like this is an issue and we'd like to avoid this unless its absolutely necessary, especially as there are other things we are working on and looking into which will likely have a larger impact on performance.

**Comment by bjzhjing** [comment]
"--emit", "asm", will break cargo clippy, but slp setting will not.

Here is the data in my testing with the latest master 8f603fc ("noise: replace shouty-case HASH/HMAC/SEAL/OPEN macros with normal functions"):

1. without "llvm-args=-slp-recursion-max-depth=1024"

> test tests::bench_blake2s_hash_1024b          ... bench:       2,498 ns/iter (+/- 4)
test tests::bench_blake2s_hash_128b           ... bench:         359 ns/iter (+/- 0)
test tests::bench_chacha20poly1305_open_192b  ... bench:         720 ns/iter (+/- 6)
test tests::bench_chacha20poly1305_seal_192b  ... bench:         825 ns/iter (+/- 2)
test tests::bench_chacha20poly1305_seal_512b  ... bench:       1,995 ns/iter (+/- 14)
test tests::bench_chacha20poly1305_seal_8192b ... bench:      29,180 ns/iter (+/- 53)
test tests::bench_x25519_public_key           ... bench:      22,706 ns/iter (+/- 101)
test tests::bench_x25519_shared_key           ... bench:      68,920 ns/iter (+/- 236)

2. with "llvm-args=-slp-recursion-max-depth=1024"

> test tests::bench_blake2s_hash_1024b          ... bench:       2,727 ns/iter (+/- 10)
test tests::bench_blake2s_hash_128b           ... bench:         376 ns/iter (+/- 1)
test tests::bench_chacha20poly1305_open_192b  ... bench:         670 ns/iter (+/- 2)
test tests::bench_chacha20poly1305_seal_192b  ... bench:         630 ns/iter (+/- 1)
test tests::bench_chacha20poly1305_seal_512b  ... bench:       1,207 ns/iter (+/- 4)
test tests::bench_chacha20poly1305_seal_8192b ... bench:      16,555 ns/iter (+/- 38)
test tests::bench_x25519_public_key           ... bench:      22,419 ns/iter (+/- 207)
test tests::bench_x25519_shared_key           ... bench:      69,182 ns/iter (+/- 318)

ChaCha20-poly1305 cases have very good performance improvment in #2 vs #1.

**Comment by bjzhjing** [comment]
I do not see such heavy regression in my testing, can you share what environment you're working on? 
Additionally, you said "switching to ring for the chacha20 implementation", does it mean the current ChaCha20 implementation under "boringtun/src/crypto/chacha20poly1305_custom" will be totally dropped?

**Comment by Noah-Kennedy** [comment]
@bjzhjing this was done on an otherwise unloaded laptop with an intel i7-1185G7. I'm going to do some runs with my Ryzen 9 5950X right now.

**Comment by Noah-Kennedy** [comment]
Seems fine on this one.

```
     Running benches/crypto_benches/main.rs (target/release/deps/crypto_benches-5377b0d2238aaeb2)
Gnuplot not found, using plotters backend
Benchmarking chacha20poly1305/chacha20poly1305_ring/128: Collecting 1000 samples in estimated 5.0587 s (32M iterat                                                                                                                  chacha20poly1305/chacha20poly1305_ring/128                        
                        time:   [163.57 ns 163.69 ns 163.81 ns]
                        thrpt:  [745.19 MiB/s 745.75 MiB/s 746.30 MiB/s]
                 change:
                        time:   [+4.8616% +5.1160% +5.3681%] (p = 0.00 < 0.05)
                        thrpt:  [-5.0947% -4.8670% -4.6362%]
                        Performance has regressed.
Found 22 outliers among 1000 measurements (2.20%)
  8 (0.80%) low mild
  12 (1.20%) high mild
  2 (0.20%) high severe
Benchmarking chacha20poly1305/chacha20poly1305_non_ring/128: Collecting 1000 samples in estimated 5.5515 s (4.0M i                                                                                                                  chacha20poly1305/chacha20poly1305_non_ring/128                        
                        time:   [1.3871 us 1.3898 us 1.3929 us]
                        thrpt:  [87.636 MiB/s 87.831 MiB/s 88.007 MiB/s]
                 change:
                        time:   [-0.1529% +0.0532% +0.2374%] (p = 0.61 > 0.05)
                        thrpt:  [-0.2368% -0.0531% +0.1532%]
                        No change in performance detected.
Found 33 outliers among 1000 measurements (3.30%)
  28 (2.80%) low mild
  2 (0.20%) high mild
  3 (0.30%) high severe
Benchmarking chacha20poly1305/chacha20poly1305_custom/128: Collecting 1000 samples in estimated 5.0004 s (23M iter                                                                                                                  chacha20poly1305/chacha20poly1305_custom/128                        
                        time:   [226.56 ns 226.87 ns 227.21 ns]
                        thrpt:  [537.27 MiB/s 538.05 MiB/s 538.79 MiB/s]
                 change:
                        time:   [-32.431% -32.317% -32.197%] (p = 0.00 < 0.05)
                        thrpt:  [+47.486% +47.747% +47.997%]
                        Performance has improved.
Found 57 outliers among 1000 measurements (5.70%)
  38 (3.80%) high mild
  19 (1.90%) high severe
Benchmarking chacha20poly1305/chacha20poly1305_ring/192: Collecting 1000 samples in estimated 5.0270 s (28M iterat                                                                                                                  chacha20poly1305/chacha20poly1305_ring/192                        
                        time:   [178.33 ns 178.45 ns 178.57 ns]
                        thrpt:  [1.0014 GiB/s 1.0020 GiB/s 1.0027 GiB/s]
                 change:
                        time:   [+4.5067% +4.5748% +4.6400%] (p = 0.00 < 0.05)
                        thrpt:  [-4.4342% -4.3746% -4.3124%]
                        Performance has regressed.
Benchmarking chacha20poly1305/chacha20poly1305_non_ring/192: Collecting 1000 samples in estimated 5.5447 s (4.0M i                                                                                                                  chacha20poly1305/chacha20poly1305_non_ring/192                        
                        time:   [1.3261 us 1.3268 us 1.3276 us]
                        thrpt:  [137.92 MiB/s 138.00 MiB/s 138.08 MiB/s]
                 change:
                        time:   [-5.2307% -5.1025% -4.9759%] (p = 0.00 < 0.05)
                        thrpt:  [+5.2365% +5.3769% +5.5195%]
                        Performance has improved.
Benchmarking chacha20poly1305/chacha20poly1305_custom/192: Collecting 1000 samples in estimated 5.0387 s (16M iter                                                                                                                  chacha20poly1305/chacha20poly1305_custom/192                        
                        time:   [332.49 ns 332.92 ns 333.38 ns]
                        thrpt:  [549.24 MiB/s 549.99 MiB/s 550.71 MiB/s]
                 change:
                        time:   [-31.154% -31.046% -30.934%] (p = 0.00 < 0.05)
                        thrpt:  [+44.789% +45.025% +45.251%]
                        Performance has improved.
Found 5 outliers among 1000 measurements (0.50%)
  1 (0.10%) high mild
  4 (0.40%) high severe
Benchmarking chacha20poly1305/chacha20poly1305_ring/1400: Collecting 1000 samples in estimated 5.1380 s (8.5M iter                                                                                                                  chacha20poly1305/chacha20poly1305_ring/1400                        
                        time:   [597.67 ns 598.32 ns 598.99 ns]
                        thrpt:  [2.1767 GiB/s 2.1792 GiB/s 2.1815 GiB/s]
                 change:
                        time:   [+4.0005% +4.1887% +4.3709%] (p = 0.00 < 0.05)
                        thrpt:  [-4.1879% -4.0203% -3.8466%]
                        Performance has regressed.
Found 15 outliers among 1000 measurements (1.50%)
  15 (1.50%) low mild
Benchmarking chacha20poly1305/chacha20poly1305_non_ring/1400: Collecting 1000 samples in estimated 5.6175 s (2.5M                                                                                                                   chacha20poly1305/chacha20poly1305_non_ring/1400                        
                        time:   [2.2293 us 2.2308 us 2.2322 us]
                        thrpt:  [598.12 MiB/s 598.51 MiB/s 598.92 MiB/s]
                 change:
                        time:   [-1.1222% -0.9872% -0.8552%] (p = 0.00 < 0.05)
                        thrpt:  [+0.8625% +0.9971% +1.1349%]
                        Change within noise threshold.
Benchmarking chacha20poly1305/chacha20poly1305_custom/1400: Collecting 1000 samples in estimated 5.0018 s (3.0M it                                                                                                                  chacha20poly1305/chacha20poly1305_custom/1400                        
                        time:   [1.6772 us 1.6788 us 1.6805 us]
                        thrpt:  [794.48 MiB/s 795.31 MiB/s 796.04 MiB/s]
                 change:
                        time:   [-44.053% -43.961% -43.869%] (p = 0.00 < 0.05)
                        thrpt:  [+78.156% +78.447% +78.742%]
                        Performance has improved.
Found 3 outliers among 1000 measurements (0.30%)
  2 (0.20%) high mild
  1 (0.10%) high severe
Benchmarking chacha20poly1305/chacha20poly1305_ring/8192: Collecting 1000 samples in estimated 5.1162 s (2.0M iter                                                                                                                  chacha20poly1305/chacha20poly1305_ring/8192                        
                        time:   [2.5430 us 2.5442 us 2.5456 us]
                        thrpt:  [2.9971 GiB/s 2.9987 GiB/s 3.0002 GiB/s]
                 change:
                        time:   [-1.6682% -1.5031% -1.3521%] (p = 0.00 < 0.05)
                        thrpt:  [+1.3706% +1.5260% +1.6965%]
                        Performance has improved.
Found 1 outliers among 1000 measurements (0.10%)
  1 (0.10%) high mild
Benchmarking chacha20poly1305/chacha20poly1305_non_ring/8192: Collecting 1000 samples in estimated 6.5138 s (1.0M                                                                                                                   chacha20poly1305/chacha20poly1305_non_ring/8192                        
                        time:   [6.4657 us 6.4690 us 6.4725 us]
                        thrpt:  [1.1787 GiB/s 1.1794 GiB/s 1.1800 GiB/s]
                 change:
                        time:   [-0.1704% -0.1081% -0.0479%] (p = 0.00 < 0.05)
                        thrpt:  [+0.0479% +0.1082% +0.1707%]
                        Change within noise threshold.
Found 1 outliers among 1000 measurements (0.10%)
  1 (0.10%) high mild
Benchmarking chacha20poly1305/chacha20poly1305_custom/8192: Collecting 1000 samples in estimated 8.8072 s (1.0M it                                                                                                                  chacha20poly1305/chacha20poly1305_custom/8192                        
                        time:   [8.5353 us 8.5539 us 8.5734 us]
                        thrpt:  [911.25 MiB/s 913.33 MiB/s 915.32 MiB/s]
                 change:
                        time:   [-49.202% -49.045% -48.879%] (p = 0.00 < 0.05)
                        thrpt:  [+95.613% +96.251% +96.859%]
                        Performance has improved.

blake2s/128             time:   [206.79 ns 206.93 ns 207.07 ns]                         
                        thrpt:  [589.51 MiB/s 589.91 MiB/s 590.31 MiB/s]
                 change:
                        time:   [+18.892% +19.041% +19.189%] (p = 0.00 < 0.05)
                        thrpt:  [-16.100% -15.995% -15.890%]
                        Performance has regressed.
Found 19 outliers among 1000 measurements (1.90%)
  19 (1.90%) high mild
blake2s/1024            time:   [1.6417 us 1.6453 us 1.6488 us]                           
                        thrpt:  [592.29 MiB/s 593.56 MiB/s 594.85 MiB/s]
                 change:
                        time:   [+25.794% +26.054% +26.335%] (p = 0.00 < 0.05)
                        thrpt:  [-20.846% -20.669% -20.505%]
                        Performance has regressed.
Found 155 outliers among 1000 measurements (15.50%)
  155 (15.50%) high mild

Benchmarking x25519_shared_key/x25519_shared_key_dalek: Collecting 1000 samples in estimated 5.0022 s (120k iterat                                                                                                                  x25519_shared_key/x25519_shared_key_dalek                        
                        time:   [40.540 us 40.583 us 40.627 us]
                        change: [-7.7492% -7.5935% -7.4401%] (p = 0.00 < 0.05)
                        Performance has improved.
Found 69 outliers among 1000 measurements (6.90%)
  24 (2.40%) high mild
  45 (4.50%) high severe
Benchmarking x25519_shared_key/x25519_shared_key_ring: Collecting 1000 samples in estimated 5.0253 s (157k iterati                                                                                                                  x25519_shared_key/x25519_shared_key_ring                        
                        time:   [31.423 us 31.453 us 31.487 us]
                        change: [+0.5761% +0.6998% +0.8448%] (p = 0.00 < 0.05)
                        Change within noise threshold.
Found 12 outliers among 1000 measurements (1.20%)
  10 (1.00%) high mild
  2 (0.20%) high severe

Benchmarking x25519_public_key/x25519_public_key_dalek: Warming up for 3.0000 s
Warning: Unable to complete 1000 samples in 5.0s. You may wish to increase target time to 6.6s, enable flat sampling, or reduce sample count to 610.
Benchmarking x25519_public_key/x25519_public_key_dalek: Collecting 1000 samples in estimated 6.6469 s (500k iterat                                                                                                                  x25519_public_key/x25519_public_key_dalek                        
                        time:   [13.151 us 13.163 us 13.174 us]
                        change: [+1.2375% +1.3387% +1.4424%] (p = 0.00 < 0.05)
                        Performance has regressed.
Benchmarking x25519_public_key/x25519_public_key_ring: Warming up for 3.0000 s
Warning: Unable to complete 1000 samples in 5.0s. You may wish to increase target time to 6.1s, enable flat sampling, or reduce sample count to 640.
Benchmarking x25519_public_key/x25519_public_key_ring: Collecting 1000 samples in estimated 6.0809 s (500k iterati                                                                                                                  x25519_public_key/x25519_public_key_ring                        
                        time:   [12.058 us 12.065 us 12.072 us]
                        change: [+3.5395% +3.7504% +3.9519%] (p = 0.00 < 0.05)
                        Performance has regressed.
Found 2 outliers among 1000 measurements (0.20%)
  2 (0.20%) high severe

     Running unittests src/main.rs (target/release/deps/boringtun_cli-5668a1b9752891e0)

running 0 tests

test result: ok. 0 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out; finished in 0.00s


Process finished with exit code 0

```

**Comment by Noah-Kennedy** [comment]
That last one seems to show this change as having no real impact on the cryptography implementations we are moving to or using within margin of error.

**Comment by bjzhjing** [comment]
@Noah-Kennedy Thanks for providing the data! My local testing also indicates that the slp setting helps improve chacha20poly1305_custom dramatically while it has very little impact on chacha20poly1305_ring.
If you decides to remove the chacha20poly1305_custom implementation, I think this slp seeting seems not necessary.

**Comment by Noah-Kennedy** [comment]
@bjzhjing I can confirm that @jeff-hiner is currently working to get rid the custom implementation of chacha20, which will be replaced with `ring`.

Thanks for suggesting these improvements though! Had we not been moving off of this implementation, this would have been quite useful.

**Comment by bjzhjing** [comment]
Thanks for confirming! close it.

**Pull request closed without merging**
