### PR TITLE
ffi: change parsing behavior of null or invalid psk (#210)

### PR DESCRIPTION
**Pull request by Noah-Kennedy**
Change the parsing behavior so that we return null if the PSK is invalid rather than failing silently or segfaulting.

### CODE REVIEW

**Comment by wiresock** [comment]
Thanks! I have tested on Windows and I can confirm that it works as expected.

**Comment by saurik** [comment]
@Noah-Kennedy I have tested e70c10e4fa0aef1c4b360ea141d7e9ec4c7dfeba (which may or may not be the correct commit: I don't use GitHub's patch review system often).

Passing NULL works as I would expect, but passing an invalid string--I tested ""--does not: I expected new_tunnel to return NULL (as it is documented to "return NULL on failure") but instead it panicked.

```
thread '<unnamed>' panicked at 'called `Option::unwrap()` on a `None` value', src/ffi/mod.rs:281:34
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
make: *** [makefile:34: test] Aborted (core dumped)
```

(Passing RUST_BACKTRACE=1 did not add any information and the information from RUST_BACKTRACE=full is not useful. I must be losing Rust's debug symbols somewhere... I should look into that.)

(FWIW, I don't personally mind that it panicked--as I don't intend to pass an invalid string and so don't need to catch the resulting failure--but it doesn't seem like the correct thing for the API to be doing.)

**Comment by Noah-Kennedy** [comment]
Now I just need to figure out what is going on with the MacOS build.

**Comment by Noah-Kennedy** [comment]
Nevermind it was spurious

**Pull request merged**
