### PR TITLE
Handle unrecoverable read errors on the tun interface

### PR DESCRIPTION
**Pull request by poupas**
Proposed patch for #125

### CODE REVIEW

**Comment by poupas** [comment]
> `if let {} else if let {}` could be a `match`.

Thank you for the comment. Should I change it?

**Comment by kornelski** [comment]
Yes, I think it'd make the code clearer/more idiomatic

**Comment by vkrasnov** [comment]
@poupas could you squash the PR into a single commit. When I use github to squash and merge it has a habit of removing the commit author.

**Comment by Lin-Buo-Ren** [comment]
@kornelski 

Could you please make a release that include this fix?  I believe a bug that making one's server run at 100% CPU usage for infinite time pretty much a valid reasoning to do so:

Screenshot

**Pull request merged**
