### PR TITLE
Stack over flow issue on running `wg add conf` or `wg set conf` for large config files.

### PR DESCRIPTION
**Pull request by zaid3tech**
I faced this issue when I tried to load a config file with almost 24000 peers. Tunnel was running on foreground and I got the error with a crash explained in #222.
Few points on this regard.

- I do not have the exact figure of peer after which the tunnel crashes.
- Apparent reason for the crash seems to be the recursive call to api_set_peer.

### CODE REVIEW

**Comment by zaid3tech** [comment]
@Noah-Kennedy please look into it whenever you get a chance, also can you please give me some hints about the 3 failing tests, whenever you get a chance.
Thanks

**Comment by Noah-Kennedy** [comment]
@zaid3tech run `cargo fmt` and push again.

**Comment by Noah-Kennedy** [comment]
@zaid3tech we just reshuffled the structure of the repo a bit and split out boringtun into multiple crates, you need to fix a few merge conflicts. Fortunately this should be simple. We just extracted the binary part of boringtun into a new crate, boringtun-cli.

**Comment by zaid3tech** [comment]
@Noah-Kennedy Thanks for keeping me informed about the changes 👍🏼

**Review by Noah-Kennedy — APPROVED** [review]

**Pull request merged**
