### PR TITLE
Redirect stdout and stderr to log file when daemonized (#154)

### PR DESCRIPTION
**Pull request by mikma**

### CODE REVIEW

**Comment by dgkh1975** [comment]
thamnks for goin

**Comment by dgkh1975** [comment]
hi

**Comment by dgkh1975** [comment]
Go

**Comment by dgkh1975** [comment]
Yea

**Comment by Noah-Kennedy** [comment]
Closing this as boringtun now uses tracing and this PR has gone over a year without any activity.

**Pull request closed without merging**
