### PR TITLE
Boringtun contract

### PR DESCRIPTION
**Pull request by ErastusMunala**
1 in the server side generate a key pair with boringtun, obtain an
NEAR implicit account ID and the private key. They are stored in the
normal boringtun configuration file.

### CODE REVIEW

**Review by alanesmizi — APPROVED** [review]

**Review by alanesmizi — COMMENTED** [review]
Ok

**Review by alanesmizi — APPROVED** [review]
approved

**Review by alanesmizi — APPROVED** [review]
approved

**Review by alanesmizi — APPROVED** [review]
approved

**Comment by Noah-Kennedy** [comment]
I don't think this is a good fit for this project.

**Pull request closed without merging**
